/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import modelo.*;

/**
 *
 * @author andre
 */
public class GUIDiagnostico extends javax.swing.JFrame {
    
    Cita cita;
    /**
     * Creates new form GUIDiagnostico
     * @param cita
     */
    public GUIDiagnostico(Cita cita){
        initComponents();
        this.cita = cita;
        this.setTitle("Diagnostico para: " + cita.getPaciente().getNombreCompleto());
        this.setIconImage(new ImageIcon(getClass().getResource("/images/iconDiagnostico.jpg")).getImage());
        this.getContentPane().setBackground(new Color(0xE0E0F8));
        this.setVisible(true);
        this.setLocationRelativeTo(null);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaPadecimiento = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaSintomas = new javax.swing.JTextArea();
        lblSintomas = new javax.swing.JLabel();
        lblPadecimiento = new javax.swing.JLabel();
        btnGenerarReceta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtAreaPadecimiento.setColumns(20);
        txtAreaPadecimiento.setRows(5);
        jScrollPane1.setViewportView(txtAreaPadecimiento);

        txtAreaSintomas.setColumns(20);
        txtAreaSintomas.setRows(5);
        jScrollPane2.setViewportView(txtAreaSintomas);

        lblSintomas.setText("Sintomas");

        lblPadecimiento.setText("Padecimiento");

        btnGenerarReceta.setText("Generar Receta");
        btnGenerarReceta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarRecetaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPadecimiento)
                            .addComponent(lblSintomas))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnGenerarReceta)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSintomas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(lblPadecimiento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGenerarReceta)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarRecetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarRecetaActionPerformed
        if(txtAreaPadecimiento.getText().length()!=0&&txtAreaSintomas.getText().length()!=0){
            String sintomas = txtAreaSintomas.getText(),
            temp="";
            ArrayList<String> sintomasArray = new ArrayList<>();
            for(int i = 0 ; i<sintomas.length();i++){
                if(sintomas.charAt(i)==','||sintomas.charAt(i)=='\n'){
                    sintomasArray.add(temp);
                    temp = "";
                }else{
                    temp+=sintomas.charAt(i);
                }
            }
            cita.getMedico().emiteDiagnostico(cita, sintomasArray.toArray(new String[sintomasArray.size()]), txtAreaPadecimiento.getText());
            GUIReceta receta = new GUIReceta(cita);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null,"Rellene todos los campos","Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGenerarRecetaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerarReceta;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblPadecimiento;
    private javax.swing.JLabel lblSintomas;
    private javax.swing.JTextArea txtAreaPadecimiento;
    private javax.swing.JTextArea txtAreaSintomas;
    // End of variables declaration//GEN-END:variables
}
