/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Factory;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.Calendar;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import modelo.*;

/**
 *
 * @author andre
 */
public class GUIMedico extends javax.swing.JFrame {

    /**
     * Creates new form GUIMedico
     */
    private Cita cita;
    public GUIMedico(Medico medico) {
        initComponents();
        cita = new Cita();
        cita.setMedico(medico);
        this.setTitle("Médico: "+medico.getNombreCompleto());
        this.setIconImage(new ImageIcon(getClass().getResource("/images/iconMedico.jpg")).getImage());
        especialidadMedico.setText(medico.getEspecialidad());
        horarioMedico.setText("Horario: "+medico.getHorarioString());
        panInfoPaciente.setVisible(false);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        this.getContentPane().setBackground(new Color(0xE0F8EC));
        panInfoPaciente.setBackground(new Color(0xE0F8EC));
        generarCBox();
    }   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        especialidadMedico = new javax.swing.JLabel();
        btnVerIfoPaciente = new javax.swing.JButton();
        panInfoPaciente = new javax.swing.JPanel();
        btnVerOtroPaciente = new javax.swing.JButton();
        txtDireccion = new javax.swing.JTextField();
        labelCURP = new javax.swing.JLabel();
        btnVerHistorialClinico = new javax.swing.JButton();
        btnDiagnostico = new javax.swing.JButton();
        txtCURP = new javax.swing.JTextField();
        labelNombre = new javax.swing.JLabel();
        labelFechaNacimiento = new javax.swing.JLabel();
        labelDireccion = new javax.swing.JLabel();
        txtNombrePaciente = new javax.swing.JTextField();
        txtFechaNacimiento = new javax.swing.JTextField();
        labelClavePaciente = new javax.swing.JLabel();
        horarioMedico = new javax.swing.JLabel();
        BTNCerrarCesion = new javax.swing.JButton();
        cBoxClaveSeguro = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Consulta");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(0, 0));
        setName("FrameDoctor"); // NOI18N
        setResizable(false);

        especialidadMedico.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        especialidadMedico.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btnVerIfoPaciente.setText("Ver Informacion");
        btnVerIfoPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerIfoPacienteActionPerformed(evt);
            }
        });

        btnVerOtroPaciente.setText("Ver otro paciente");
        btnVerOtroPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerOtroPacienteActionPerformed(evt);
            }
        });

        txtDireccion.setEditable(false);
        txtDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionActionPerformed(evt);
            }
        });

        labelCURP.setText("CURP:");

        btnVerHistorialClinico.setText("Ver HistorialClinico");
        btnVerHistorialClinico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerHistorialClinicoActionPerformed(evt);
            }
        });

        btnDiagnostico.setText("Crear Diagnóstico");
        btnDiagnostico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiagnosticoActionPerformed(evt);
            }
        });

        txtCURP.setEditable(false);
        txtCURP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCURPActionPerformed(evt);
            }
        });
        txtCURP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCURPKeyReleased(evt);
            }
        });

        labelNombre.setText("Nombre:");

        labelFechaNacimiento.setText("Fecha de nacimiento:");

        labelDireccion.setText("Dirección:");

        txtNombrePaciente.setEditable(false);

        txtFechaNacimiento.setEditable(false);
        txtFechaNacimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaNacimientoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panInfoPacienteLayout = new javax.swing.GroupLayout(panInfoPaciente);
        panInfoPaciente.setLayout(panInfoPacienteLayout);
        panInfoPacienteLayout.setHorizontalGroup(
            panInfoPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panInfoPacienteLayout.createSequentialGroup()
                .addGroup(panInfoPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panInfoPacienteLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(labelNombre))
                    .addGroup(panInfoPacienteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelCURP))
                    .addGroup(panInfoPacienteLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(panInfoPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelDireccion)
                            .addComponent(labelFechaNacimiento))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(panInfoPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombrePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCURP, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panInfoPacienteLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panInfoPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnVerOtroPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDiagnostico, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVerHistorialClinico, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(84, 84, 84))
        );
        panInfoPacienteLayout.setVerticalGroup(
            panInfoPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panInfoPacienteLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(panInfoPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCURP)
                    .addComponent(labelCURP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panInfoPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombre)
                    .addComponent(txtNombrePaciente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panInfoPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFechaNacimiento)
                    .addComponent(txtFechaNacimiento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panInfoPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDireccion)
                    .addComponent(labelDireccion))
                .addGap(26, 26, 26)
                .addComponent(btnVerHistorialClinico)
                .addGap(18, 18, 18)
                .addComponent(btnDiagnostico)
                .addGap(18, 18, 18)
                .addComponent(btnVerOtroPaciente)
                .addGap(30, 30, 30))
        );

        labelClavePaciente.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        labelClavePaciente.setText("Clave de Seguro del Paciente:");

        horarioMedico.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        horarioMedico.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        BTNCerrarCesion.setText("Cerrar sesión");
        BTNCerrarCesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCerrarCesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(especialidadMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(horarioMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(BTNCerrarCesion)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelClavePaciente)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cBoxClaveSeguro, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnVerIfoPaciente)))
                                .addGap(20, 20, 20)))
                        .addGap(13, 13, 13))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panInfoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(especialidadMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(horarioMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelClavePaciente)
                    .addComponent(btnVerIfoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cBoxClaveSeguro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(panInfoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BTNCerrarCesion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCURPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCURPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCURPActionPerformed

    private void txtFechaNacimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaNacimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaNacimientoActionPerformed

    private void txtDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionActionPerformed

    
    private void txtCURPKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCURPKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCURPKeyReleased

    private void btnVerIfoPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerIfoPacienteActionPerformed
            this.mostrarInfoPaciente();
    }//GEN-LAST:event_btnVerIfoPacienteActionPerformed

    private void btnVerOtroPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerOtroPacienteActionPerformed
        panInfoPaciente.setVisible(false);
    }//GEN-LAST:event_btnVerOtroPacienteActionPerformed

    private void btnVerHistorialClinicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerHistorialClinicoActionPerformed
        GUIHistorialClinico historial = new GUIHistorialClinico(cita.getPaciente());
    }//GEN-LAST:event_btnVerHistorialClinicoActionPerformed

    private void btnDiagnosticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiagnosticoActionPerformed
       GUIDiagnostico diagnostico = new GUIDiagnostico(cita);
    }//GEN-LAST:event_btnDiagnosticoActionPerformed

    private void BTNCerrarCesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCerrarCesionActionPerformed
        GUILogin login = new GUILogin();
        this.dispose();
    }//GEN-LAST:event_BTNCerrarCesionActionPerformed

    private void mostrarInfoPaciente(){
            boolean encontrado=false;
            String claveSeguro = cBoxClaveSeguro.getSelectedItem().toString();
            for(Paciente pac: Factory.getPacientes()){
                if(pac.getClaveSeguro().equals(claveSeguro)){
                    if(pac.getHistorial()== null){
                        btnVerHistorialClinico.setText("No hay Historial");
                        btnVerHistorialClinico.setEnabled(false);
                    }
                    encontrado = true;
                    txtNombrePaciente.setText(pac.getNombreCompleto());
                    //txtNombrePaciente.setEditable(false);
                    txtFechaNacimiento.setText(Factory.FORMATO_FECHA.format(pac.getFechaNacimiento().getTime()));
                    //txtFechaNacimiento.setEditable(false);
                    txtCURP.setText(pac.getCURP());
                    //txtCURP.setEditable(false);
                    txtDireccion.setText(pac.getDomicilio());
                    //txtDireccion.setEditable(false);
                    cita.setPaciente(pac);
                    panInfoPaciente.setVisible(true);
                    break;
                }
            }
            if(!encontrado){
                JOptionPane.showMessageDialog(null,"Error: Paciente no encontrado","Error en busqueda", JOptionPane.WARNING_MESSAGE);
            }
    }
    
    private void generarCBox(){
        for(Paciente p: Factory.getPacientes()){
            cBoxClaveSeguro.addItem(p.getClaveSeguro());
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNCerrarCesion;
    private javax.swing.JButton btnDiagnostico;
    private javax.swing.JButton btnVerHistorialClinico;
    private javax.swing.JButton btnVerIfoPaciente;
    private javax.swing.JButton btnVerOtroPaciente;
    private javax.swing.JComboBox<String> cBoxClaveSeguro;
    private javax.swing.JLabel especialidadMedico;
    private javax.swing.JLabel horarioMedico;
    private javax.swing.JLabel labelCURP;
    private javax.swing.JLabel labelClavePaciente;
    private javax.swing.JLabel labelDireccion;
    private javax.swing.JLabel labelFechaNacimiento;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JPanel panInfoPaciente;
    private javax.swing.JTextField txtCURP;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtFechaNacimiento;
    private javax.swing.JTextField txtNombrePaciente;
    // End of variables declaration//GEN-END:variables
}
